### ISSUE TITLE
Reupload pnket and floorp on AUR with the correct pkgname

### ISSUE THREAD

**Issue by FabioLolix** [Ablaze-MIRAI/pnket#1]
Hello, your `pnket` and `floorp` pkgbuilds on AUR are disguised-bin pkgbuilds, you're welcome to re-upload with the correct name

I have informed you several times about `floorp` but you always ignored

* pnket-bin pkgbuild https://github.com/FabioLolix/AURFIX/blob/main/p/pnket-bin/PKGBUILD
* pnket-bin diff https://github.com/FabioLolix/AURFIX/commit/d4ed045edbe2b76a55ce34dca20738d5ccbed61c (corrected several things)
* floorp-bin pkgbuild https://github.com/FabioLolix/AURFIX/blob/main/f/floorp-bin/PKGBUILD
* floorp-bin diff https://github.com/FabioLolix/AURFIX/commit/9bad22093c9c6a6a8a0a0c5cb33ea750b32271a2
* https://github.com/FabioLolix/AURFIX

**Comment by Nakanoin19** [comment]
If I changed `floorp` to `floorp-bin`, it would confuse to users.
You may be thinking, "Just change to pkgbuild, the build method". However, it takes longer than expected to build Firefox and its derivatives. Therefore, we are not going to change it for `floorp`.
But, it does not take much time to build `pnket`, so I will change to the build method from the next update that affects the CLI application.
You may not agree, but this is my best effort to respond. Please understand.

**Comment by FabioLolix** [comment]
> But, it does not take much time to build pnket, so I will change to the build method from the next update that affects the CLI application.

Here's the pkgbuild for building pnket from source:
* https://github.com/FabioLolix/AURFIX/blob/main/p/pnket/PKGBUILD
* https://wiki.archlinux.org/title/Rust_package_guidelines

***

> You may be thinking, "Just change to pkgbuild, the build method". However, it takes longer than expected to build Firefox and its derivatives.

I know; I build and maintain a lot of stuff on the AUR, that's why I haven't suggested it

> If I changed floorp to floorp-bin, it would confuse to users.

> Therefore, we are not going to change it for floorp.

These rules are for everyone on the AUR, if it is open source and it repackage prebuilds binaries it must be renamed with `-bin` suffix, you have been informed for a lot of time now for a simple change. I don't agree; just do it.
